name: CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-scan:
    name: Build, Test & Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest || echo "No tests found"

      # Generate lowercase IMAGE_NAME and save to $GITHUB_ENV
      - name: Set Docker image name (lowercase)
        run: |
          OWNER_LC="${GITHUB_REPOSITORY_OWNER,,}"
          echo "IMAGE_NAME=ghcr.io/$OWNER_LC/branch-loan-api" >> $GITHUB_ENV

      # Build Docker Image
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .

      # Install Trivy scanner
      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          ignore-unfixed: true

      # Scan Docker image
      - name: Trivy Image Scan
        run: trivy image --exit-code 0 --severity HIGH,CRITICAL $IMAGE_NAME:${{ github.sha }}

  push-image:
    name: Push Image to GHCR
    needs: build-test-scan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Generate lowercase IMAGE_NAME again in this job
      - name: Set Docker image name (lowercase)
        run: |
          OWNER_LC="${GITHUB_REPOSITORY_OWNER,,}"
          echo "IMAGE_NAME=ghcr.io/$OWNER_LC/branch-loan-api" >> $GITHUB_ENV

      # Login to GHCR
      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build Docker Image for pushing
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Tag Image as Latest
        run: docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest

      - name: Push Images
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest
